#!/bin/bash

NAME=seedTest
URL_LOCATION="seedtest"
CORENAME=OxygenCrawl_seedTest

if ! [[ "$1" =~ ^[0-9]+$ ]]
  then 
    echo Please enter the number of crawl rounds as parameter.
  else
	source $NUTCH_RUNTIME_HOME/bin/my_crawl $1  
fi
